### ISSUE TITLE
release for conda

### ISSUE THREAD

**Issue by martindurant** [milesgranger/pyrus-cramjam#3]
This seems like a very useful package, if it is small, fast and compliant!
I'm sure users would appreciate installing pre-compiled versions from conda. 
https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by martindurant** [comment]
ping here - I believe this step would help adoption

**Comment by milesgranger** [comment]
I've made a feeble attempt. I don't use Conda, and as the packages are already pre-compiled as `.whl` files on PyPi I wasn't sure how to again pre-compile them via a Conda Recipe, so thought it was possible to just use the existing wheels with `--no-deps`. Maybe you could give me a small pointer? Thanks!

https://github.com/conda-forge/staged-recipes/pull/12159

**Comment by martindurant** [comment]
If you continue to pole the conda-forge maintainers, they will eventually show the "right" way to do things!
By the way, do you have any benchmarking for the various algorithms?

**Comment by milesgranger** [comment]
I did some a while ago, if I remember correctly the snappy variant was a touch slower than `python-snappy` but gzip was nearly twice as fast as the the std lib Python. I didn't compare the other variants to other Python implementations, however, it's probably a good thing to create some basic comparisons at least. :+1:

**Comment by milesgranger** [comment]
Thanks for the bit of help, even though we still can't get it to use the wheels on PyPi it seems. 

Maybe I'm being a bit dense, but I'm struggling to understand why having the package available on conda-forge is advantageous to the defacto standard pypi, namely because the package is already pre-compiled on pypi. [This bit of documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) seems to suggest that conda's `environment.yml` file can handle `pip` dependencies as well.

Additionally, it seems with each new release, for example [v1.3.0](https://github.com/milesgranger/pyrus-cramjam/releases/tag/v1.3.0), I would need to fork and update the recipe; whereas with pypi, it's automated after simply creating the tag on Github. 

Don't get me wrong, I'm still open for trying to get it on conda-forge, it's just that I don't fully understand the benefit to it yet, and that it will cause me more work for releases. :thinking:

**Comment by milesgranger** [comment]
Hi @martindurant 

For the second point about benchmarking, I added an update with better benchmarking in #12 so you can see those now [here in the benchmarks](https://github.com/milesgranger/pyrus-cramjam/tree/master/benchmarks) more-or-less on par with `python-snappy`. Let me know if you have any suggestions! :smile:

**Comment by martindurant** [comment]
Thanks!
Someone *very motivated* might try to find the reasons for the differences.
Isn't zstd missing, or is that not implemented?

**Comment by milesgranger** [comment]
ah indeed, I must have glossed over it. Benchmarks have been updated, thanks! :+1:
