### ISSUE TITLE
Cramjam wrong architecture error when installing on M1 with conda (mambaforge)

### ISSUE THREAD

**Issue by rrpelgrim** [milesgranger/pyrus-cramjam#67]
I'm working on Apple M1 with a mambaforge deployment of conda.
When trying to save a dataframe to parquet using `fastparquet` I'm getting the following error:

```
ImportError: dlopen(/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so: mach-o, but wrong architecture
```

Seems like conda is giving me the wrong version of `cramjam`?

MRE:

`conda create -n cramjam`
`conda install cramjam ipython`
`ipython`
`import cramjam`

```
ImportError: dlopen(/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/rpelgrim/mambaforge/envs/cramjam/lib/python3.9/site-packages/cramjam.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by milesgranger** [comment]
Hi, 
I have no real experience with Apple M1.
What happens if you install from `pip`? The platform support is a bit larger on PyPi I think.

**Comment by rrpelgrim** [comment]
That works. Thanks! 🙏

**Comment by rrpelgrim** [comment]
Is there a way to notify `conda`/ `mambaforge` that something is up with the `cramjam` version I'm getting from them?

**Comment by milesgranger** [comment]
Great!

You can open an issue over at https://github.com/conda-forge/cramjam-feedstock 

Basically, I'm a bit lazy. Here with GitHub actions we maintain compiled wheels for most all platforms. However, it seems Anaconda can't re-use these wheels for some reason, especially since they have no dependencies. _Therefore_ we need to re-implement the build process for said platforms in that feedstock for Anaconda. And well, it's a pain, so I haven't bothered to do it; just the major platforms are done other there, as I remember. (Sorry!)

Closing this on here, but feel free to reference it in the issue in cramjam-feedstock repo. :+1:
